# Generated by Django 3.2.9 on 2021-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app_advanced', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('question', 'Pytanie'), ('other', 'Inne')], max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
